### ISSUE TITLE
这两是同一个吗

### ISSUE THREAD

**Issue by lijiancheng** [weilao/gulp-include-tag#2]
var htmlIncluder = require('gulp-tag-include');
var includeTag = require('gulp-include-tag');

第一个失效后 我用node脚本写了一个替代, 今天发现了一个颠倒了名字的, 功能一模一样

**Comment by ValorLin** [comment]
不是同一个东西。
我的这个工具的主项目是 [include-tag](https://github.com/weilao/include-tag)，
有浏览器版和 node 版两个版本的程序，此项目只是对这 `include-tag` 的简单封装。

gulp-tag-include 这个插件并不是我写的，并不了解。。。
楼主可以根据自己的需求来选择。
如果在使用我这个插件的过程中发现了什么问题，欢迎反馈、提交 pr，帮助我改进这个项目。
